# Generated by Django 4.1.5 on 2023-01-07 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('access_token', models.CharField(max_length=50, null=True)),
                ('weight', models.FloatField(null=True)),
                ('sex', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('follower_count', models.IntegerField(null=True)),
                ('friend_count', models.IntegerField(null=True)),
                ('measurement_preference', models.CharField(max_length=50, null=True)),
                ('ftp', models.IntegerField(null=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('strava_creation_date', models.DateTimeField(blank=True, null=True)),
                ('first_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='First activity ')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Last activity ')),
                ('act_number', models.IntegerField(null=True, verbose_name='Number of activities ')),
                ('year_run_objective', models.IntegerField(default=500, verbose_name='Year run target (km) ')),
                ('year_ride_objective', models.IntegerField(default=500, verbose_name='Year ride target (km) ')),
            ],
            options={
                'ordering': ['-user_id'],
            },
        ),
    ]
